#!/usr/bin/env python3
"""
Krea 2 LoRA training orchestrator.

⚠️ STATUS: Krea 2 model is downloaded but NOT YET TESTED for LoRA training.
The training configuration is based on FLUX architecture family assumptions.
Validation required before production use.

Usage:
    python3 train_lora_krea2.py --character "Roxanne" --images-dir /path/to/images/
    python3 train_lora_krea2.py --all --base-dir ~/ComfyUI/output/lora_kontext/
    python3 train_lora_krea2.py --character "Roxanne" --resume

Requirements:
    - kohya_ss or ai-toolkit installed
    - Krea 2 int8 model downloaded
    - 20 training images per character (1024x1024 or 768x768)
"""

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path
from datetime import datetime


# ── Default Paths ──────────────────────────────────────────────────────────

DEFAULT_MODEL = os.path.expanduser(
    "~/ComfyUI/models/diffusion_models/krea2_turbo_int8_convrot.safetensors"
)
DEFAULT_OUTPUT = os.path.expanduser("~/.cache/lora/")
DEFAULT_DATASET = os.path.expanduser("~/ComfyUI/output/lora_kontext/")


# ── Training Configuration ─────────────────────────────────────────────────

# kohya_ss / sd-scripts TOML config template
LORA_CONFIG_TEMPLATE = """# Auto-generated by lora-training-pipeline
# Character: {character}
# Date: {date}

[model]
pretrained_model_name_or_path = "{model_path}"
vae = null              # bundled in safetensors
clip_l = null           # bundled
t5xxl = null            # bundled

[network]
type = "lora"
rank = {rank}
alpha = {alpha}
module_dropout = {module_dropout}
conv_rank = 0
conv_alpha = 0
train_unet = true
train_text_encoder = false    # Face LoRA — skip TE to avoid identity bleed

[training]
output_dir = "{output_dir}"
output_name = "{character}_lora"
resolution = {resolution}
batch_size = {batch_size}
max_train_steps = {max_steps}
learning_rate = {lr}
lr_scheduler = "{lr_scheduler}"
lr_warmup_steps = {lr_warmup}
optimizer_type = "{optimizer}"
mixed_precision = "bf16"
fp8_base = {fp8_base}
gradient_checkpointing = {grad_ckpt}
gradient_accumulation_steps = {grad_accum}
save_every_n_steps = {save_every}
save_precision = "bf16"
logging_dir = "{log_dir}"
log_with = "tensorboard"
max_data_loader_n_workers = 2
persistent_data_loader_workers = true

[dataset]
resolution = {resolution}
batch_size = {batch_size}

[[datasets]]
resolution = {resolution}
batch_size = {batch_size}
image_dir = "{image_dir}"
caption_extension = ".txt"
num_repeats = {repeats}
enable_bucket = true
bucket_reso_steps = 64
min_bucket_reso = 512
max_bucket_reso = 1024
"""

DEFAULT_TRAINING_PARAMS = {
    "rank": 16,
    "alpha": 16,
    "module_dropout": 0.0,
    "resolution": 768,
    "batch_size": 1,
    "max_steps": 2000,
    "lr": 1e-4,
    "lr_scheduler": "cosine_with_restarts",
    "lr_warmup": 100,
    "optimizer": "adamw8bit",
    "fp8_base": True,
    "grad_ckpt": True,
    "grad_accum": 4,
    "save_every": 500,
    "repeats": 10,
}


def create_caption_files(image_dir: str, character_name: str):
    """
    Create .txt caption files for each image in the directory.
    Caption format: "A photo of {character_name}, {pose_description}"
    """
    image_dir = Path(image_dir)
    png_files = sorted(image_dir.glob("*.png")) + sorted(image_dir.glob("*.jpg"))

    # Basic caption templates — customize per character
    captions = [
        f"A photo of {character_name}, front view facing camera",
        f"A photo of {character_name}, head turned left, three-quarter profile",
        f"A photo of {character_name}, head turned right, three-quarter profile",
        f"A photo of {character_name}, left side profile",
        f"A photo of {character_name}, right side profile",
        f"A photo of {character_name}, looking up",
        f"A photo of {character_name}, looking down",
        f"A photo of {character_name}, over shoulder looking back",
        f"A photo of {character_name}, extreme close-up on face",
        f"A photo of {character_name}, eyes closed peaceful expression",
        f"A photo of {character_name}, serious intense stare",
        f"A photo of {character_name}, slight smile head tilted",
        f"A photo of {character_name}, mouth open speaking",
        f"A photo of {character_name}, dynamic action hair blowing",
        f"A photo of {character_name}, leaning forward engaged",
        f"A photo of {character_name}, half-body shot arms crossed",
        f"A photo of {character_name}, chin on hand thoughtful",
        f"A photo of {character_name}, low angle looking down at viewer",
        f"A photo of {character_name}, high angle looking up at camera",
        f"A photo of {character_name}, head tilted right skeptical",
    ]

    created = 0
    for i, img_path in enumerate(png_files):
        caption_path = img_path.with_suffix(".txt")
        if caption_path.exists():
            continue
        caption = captions[i] if i < len(captions) else f"A photo of {character_name}"
        caption_path.write_text(caption)
        created += 1

    print(f"  Created {created} caption files in {image_dir}")
    return len(png_files)


def generate_config(
    character: str,
    image_dir: str,
    model_path: str,
    output_dir: str,
    params: dict,
) -> str:
    """Generate kohya_ss TOML config for a character."""
    char_slug = character.lower().replace(" ", "_")
    config_dir = Path(output_dir) / "configs"
    config_dir.mkdir(parents=True, exist_ok=True)

    config_path = config_dir / f"{char_slug}.toml"
    config_content = LORA_CONFIG_TEMPLATE.format(
        character=character,
        date=datetime.now().isoformat(),
        model_path=model_path,
        image_dir=image_dir,
        output_dir=output_dir,
        log_dir=str(Path(output_dir) / "logs"),
        **params,
    )
    config_path.write_text(config_content)
    print(f"  Config written: {config_path}")
    return str(config_path)


def run_training(config_path: str, dry_run: bool = False) -> bool:
    """
    Run LoRA training using kohya_ss sd-scripts or ai-toolkit.

    Returns True on success.
    """
    # Try kohya_ss first
    kohya_train = "accelerate launch --num_cpu_threads_per_process=2 sd-scripts/flux_train_network.py"

    cmd = f"{kohya_train} --config_file {config_path}"

    print(f"  Command: {cmd}")

    if dry_run:
        print("  [DRY RUN] Skipping actual training")
        return True

    try:
        result = subprocess.run(
            cmd,
            shell=True,
            cwd=os.path.expanduser("~/kohya_ss"),
            capture_output=False,
            text=True,
        )
        return result.returncode == 0
    except FileNotFoundError:
        print("  ✗ kohya_ss not found at ~/kohya_ss")
        print("  Install: git clone https://github.com/kohya-ss/sd-scripts ~/kohya_ss")
        return False


def discover_characters(base_dir: str) -> dict[str, str]:
    """Find all character subdirectories with training images."""
    base = Path(base_dir)
    if not base.exists():
        print(f"Error: Base directory not found: {base}")
        return {}

    chars = {}
    # Look for subdirectories OR individual character image groups
    for subdir in sorted(base.iterdir()):
        if subdir.is_dir():
            images = list(subdir.glob("*.png")) + list(subdir.glob("*.jpg"))
            if images:
                chars[subdir.name] = str(subdir)
        elif subdir.suffix.lower() in (".png", ".jpg"):
            # Flat directory with prefix naming: roxanne_00.png, roxanne_01.png, ...
            prefix = "_".join(subdir.stem.split("_")[:-1]) if "_" in subdir.stem else subdir.stem
            if prefix not in chars:
                chars[prefix] = str(base)

    return chars


def main():
    parser = argparse.ArgumentParser(
        description="Krea 2 LoRA training orchestrator",
        epilog="⚠️ Krea 2 training is NOT YET VALIDATED. Test with a single character first.",
    )
    parser.add_argument(
        "--character", "-c",
        help="Train a single character",
    )
    parser.add_argument(
        "--all", action="store_true",
        help="Train all characters in --base-dir",
    )
    parser.add_argument(
        "--images-dir",
        help="Directory containing training images for --character",
    )
    parser.add_argument(
        "--base-dir", default=DEFAULT_DATASET,
        help=f"Base directory for --all mode (default: {DEFAULT_DATASET})",
    )
    parser.add_argument(
        "--model", default=DEFAULT_MODEL,
        help=f"Path to Krea 2 model (default: {DEFAULT_MODEL})",
    )
    parser.add_argument(
        "--output-dir", default=DEFAULT_OUTPUT,
        help=f"Output directory for LoRA weights (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Generate configs but don't train",
    )
    parser.add_argument(
        "--skip-captions", action="store_true",
        help="Skip caption file generation",
    )
    parser.add_argument(
        "--rank", type=int, default=16,
    )
    parser.add_argument(
        "--resolution", type=int, default=768,
    )
    parser.add_argument(
        "--steps", type=int, default=2000,
    )
    parser.add_argument(
        "--resume", action="store_true",
        help="Resume from latest checkpoint",
    )
    args = parser.parse_args()

    # Validate model exists
    if not os.path.exists(args.model) and not args.dry_run:
        print(f"⚠ Model not found: {args.model}")
        print("  Download Krea 2 before training.")
        print("  (This is expected — Krea 2 training is not yet validated)")
        choice = input("Continue anyway? [y/N] ")
        if choice.lower() != "y":
            sys.exit(1)

    # Build training params
    params = {
        **DEFAULT_TRAINING_PARAMS,
        "rank": args.rank,
        "resolution": args.resolution,
        "max_steps": args.steps,
    }

    # Build character list
    to_train = {}

    if args.all:
        to_train = discover_characters(args.base_dir)
        if not to_train:
            print(f"No character directories with images found in {args.base_dir}")
            sys.exit(1)
        print(f"Found {len(to_train)} characters to train:")
        for name, path in to_train.items():
            print(f"  - {name}: {path}")
    elif args.character:
        if args.images_dir:
            to_train = {args.character: args.images_dir}
        else:
            path = os.path.join(args.base_dir, args.character.lower().replace(" ", "_"))
            if not os.path.isdir(path):
                print(f"Directory not found: {path}")
                print("Use --images-dir to specify the image directory")
                sys.exit(1)
            to_train = {args.character: path}
    else:
        parser.print_help()
        sys.exit(1)

    print(f"\nTraining parameters:")
    print(f"  Model:     {args.model}")
    print(f"  Rank/α:    {params['rank']}/{params['alpha']}")
    print(f"  Resolution:{params['resolution']}px")
    print(f"  Steps:     {params['max_steps']}")
    print(f"  LR:        {params['lr']}")
    print(f"  Optimizer: {params['optimizer']}")
    print()

    total_estimate = len(to_train) * 50 / 60  # ~50 min per character
    print(f"Training {len(to_train)} character(s)")
    print(f"Estimated time: ~{total_estimate:.1f} hours on RTX 3090")
    print()

    results = {}
    for char_name, img_dir in to_train.items():
        print(f"── Training: {char_name} ──")
        print(f"  Images: {img_dir}")

        # Create captions
        if not args.skip_captions:
            n_images = create_caption_files(img_dir, char_name)
            print(f"  Found {n_images} images")

        # Generate config
        char_output = os.path.join(args.output_dir, char_name.lower().replace(" ", "_"))
        config_path = generate_config(char_name, img_dir, args.model, char_output, params)

        # Train
        success = run_training(config_path, dry_run=args.dry_run)
        results[char_name] = {
            "success": success,
            "config": config_path,
            "output": char_output,
        }

        if success:
            print(f"  ✓ {char_name} training complete")
        else:
            print(f"  ✗ {char_name} training failed")

    # Summary
    print("\n" + "=" * 50)
    print("TRAINING SUMMARY")
    print("=" * 50)
    succeeded = sum(1 for r in results.values() if r["success"])
    failed = sum(1 for r in results.values() if not r["success"])
    print(f"  Succeeded: {succeeded}")
    print(f"  Failed:    {failed}")
    print(f"  Output:    {args.output_dir}")


if __name__ == "__main__":
    main()
